### Função de registrar novo usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nome": "paulo",
    "email": "paulo.ss.loraschi@gmail.com",
    "senha": "123"
}

### Função de fazer login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "paulo.ss.loraschi@gmail.com",
    "senha": "123"
}

### Função esqueci-senha
PUT http://localhost:3000/auth/esqueci-senha
Content-Type: application/json

{
    "email": "paulo.ss.loraschi@gmail.com",
    "senha": "1234"
}