### Rota de pegar dashborads no BD
GET http://localhost:3000/dash/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4N2UxZGNiLWI1MTEtNGRhZS04Yjg3LTY0Y2JjYzJiNjNkMCIsIm5vbWUiOiJwYXVsbyIsImVtYWlsIjoicGF1bG8uc3MubG9yYXNjaGlAZ21haWwuY29tIiwic2VuaGEiOiIkMmIkMTMkZUhBdnAvYkFzeGFSVUJxOC9jNThjZWNhY0g5V0pCc2p5eWc2VGR5UzYzcC9pZktiMW94Rk8iLCJpYXQiOjE3Mjk2ODE3MzMsImV4cCI6MTcyOTY4NTMzM30.BekcvWQafFqnGGAkIWsdLBpuJrYXyBh6fzinhZsbioY
