### Rota de get do grafico
POST http://localhost:3000/graph/
Content-Type: application/json

{
    "dashId": 26,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwibm9tZSI6InBhdWxvIiwiZW1haWwiOiJwYXVsby5zcy5sb3Jhc2NoaUBnbWFpbC5jb20iLCJzZW5oYSI6IiQyYiQxMyR6V29ma1AvaURGLkdYODhOdFEvQndlSkV6Yi9uSGVDTi5BY1hLUVJQM21WUTd1Qi5wUFNuTyIsImlhdCI6MTcyOTg1MjgzOCwiZXhwIjoxNzI5ODU2NDM4fQ.rXAoGgiDMaP39KdplH0YPp6vEC_2kksD0Q-wBT5D6wA"
}

### Rota de create graph
POST http://localhost:3000/graph/create
Content-Type: application/json

{
    "nome": "dsaf",
    "tipo": "sacasc",
    "ordem": "scac",
    "elementos": ["casc"],
    "dados": ["1"],
    "cores": ["scacs"],
    "dashId": 26,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4N2UxZGNiLWI1MTEtNGRhZS04Yjg3LTY0Y2JjYzJiNjNkMCIsIm5vbWUiOiJwYXVsaW5obyIsImVtYWlsIjoicGF1bG8uc3MubG9yYXNjaGlAZ21haWwuY29tIiwic2VuaGEiOiIkMmIkMTAkS0IxYUVYWWVIL2dPZldtL1FHajlzT3N4Wi8yU2haY1VTU00wNVlNSG5QWFdQc3puVEU5b3EiLCJpYXQiOjE3Mjk3Mjc0ODl9.urwI7iawrM8_VXmluXZUar6kFIVFN7kA2A3WneQJGfg"
}

### Rota de delete do graph
DELETE http://localhost:3000/graph/delete
Content-Type: application/json

{
    "id": 26,
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE4N2UxZGNiLWI1MTEtNGRhZS04Yjg3LTY0Y2JjYzJiNjNkMCIsIm5vbWUiOiJwYXVsaW5obyIsImVtYWlsIjoicGF1bG8uc3MubG9yYXNjaGlAZ21haWwuY29tIiwic2VuaGEiOiIkMmIkMTAkS0IxYUVYWWVIL2dPZldtL1FHajlzT3N4Wi8yU2haY1VTU00wNVlNSG5QWFdQc3puVEU5b3EiLCJpYXQiOjE3Mjk3Mjc0ODl9.urwI7iawrM8_VXmluXZUar6kFIVFN7kA2A3WneQJGfg"
}